---
- hosts: all
  name: Configure Environment
  roles:
    - satellite-install
    - tower-install
#    - laptop-configure
# change roles to "install-*" for easier reading
#Need to include extra-vars.yml for configuration
