---
- hosts: all
  name: Post Provisioning Configuration (from Satellite)

  tasks:
    - name: install ipa client
      yum:
        name: {{ item }}
        state: latest
      with_items:
        - ipa-client
        - pcp

    - name: join ipa domain
      command: ipa-client-install --server='{{ idm_hostname }}' --domain='{{ idm_domain }}' --principal='{{ idm_register_username }}' --password='{{ idm_register_password }}' --enable-dns-updates --unattended

#    - name: Copy over pubkey for remote job execution from Satellite
#      command: curl https://{{ satellite_hostname }}:9090/ssh/pubkey >> ~/.ssh/authorized_keys
