---
- hosts: all
  name: Change password

  tasks:
  - name: Backup /etc/shadow
    copy:
      src: /etc/shadow
      dest: /etc/shadow.bak
      remote_src: True

  - name: Generate the password hash (sha512)
    local_action: command python -c 'import crypt; print crypt.crypt("{{ user_defined_password }}", "$6$3dgaQk0H")'
    register: pass_hash

  - name: Update {{ account_name }} password
    user:
      name: "{{ account_name }}"
      update_password: always
      password: "{{ pass_hash.stdout }}"
