---
- name: Add mappings to /etc/hosts, This needs to call the hostname instead of having it hard coded
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: tower.demo.com, ip: 192.168.126.3 }
    - { name: satellite.demo.com, ip: 192.168.126.2 }
    - { name: rnelsonlaptop.demo.com, ip: 192.168.126.1 }
  tags: tower

- name: Register to RHN and attach RHEL Server SKU, (change to pool_ids when Ansible 2.4 is released)
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
# need ansible2.4 for pool_ids to work
    pool: '^(Employee SKU)$'
  tags: tower

- name: Disable All Repositories
  raw: subscription-manager repos --disable "*"
  tags: tower

- name: Enable Server, Extras, and Optional Repositories
  raw: subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms --enable rhel-7-server-optional-rpms
  tags: tower

- name: Enable EPEL Repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  tags: tower

- name: Install Ansible RPM
  yum:
    name: ansible
    state: latest
  tags: tower

- name: Download and Unarchive Ansible Tower Bundle Installer
  unarchive:
    src: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
    dest: /tmp
    remote_src: yes
  tags: tower

#- name: copy over 'inventory' file with updated passwords
#  tags: tower

#- name: execute setup.sh script
#  tags: tower

#- name: create orgs, teams, users, projects, templates, workflow templates
#  tags: tower
