---
#add in ssh, http, and https for firewalld
#[root@rnelsonlaptop ~]# firewall-cmd --zone=FedoraWorkstation --permanent --add-service=http
#[root@rnelsonlaptop ~]# firewall-cmd --zone=FedoraWorkstation --permanent --add-service=https
#[root@rnelsonlaptop ~]# firewall-cmd --zone=FedoraWorkstation --permanent --add-service=ssh
#set up httpd server with manifest and foreman.yml
# have "include:" lines for both?
# Use http://account-manager-stage.app.eng.rdu2.redhat.com/#create for creating custom manifest, must be on VPN
# follow https://mojo.redhat.com/docs/DOC-1102802

#=====#
#setup and configure libvirt, deploy /etc/libvirt/qemu/networks/sat-isolated.xml or create vars vile to make it pluggable


#<network>
#  <name>sat-isolated</name>
#  <uuid>97c6ab0c-6f73-4d57-b1e9-435028739651</uuid>
#  <forward mode='nat'>
#    <nat>
#      <port start='1024' end='65535'/>
#    </nat>
#  </forward>
#  <bridge name='virbr3' stp='on' delay='0'/>
#  <mac address='52:54:00:1e:1b:10'/>
#  <ip address='192.168.126.1' netmask='255.255.255.0'>
#  </ip>
#</network>

#=====#
#Define it, start it, and autostart it in libvirt

#virsh net-define /etc/libvirt/qemu/networks/sat-isolated.xml
#virsh net-start sat-isolated
#virsh net-autostart sat-isolated
#=====#
#Deploy /etc/libvirt/libvirtd.conf (we need this to setup the libvirt compute resource)

#listen_tls = 0
#listen_tcp = 1
#tcp_port = "16509"
#auth_tcp = "none"
#=====#
#At least on recent versions of Fedora , you have to edit /etc/sysconfig/libvirtd and make sure you have this line uncommented:

#LIBVIRTD_ARGS="--listen"
#=====#
#Restart libvirtd

#systemctl restart libvirtd  (or service libvirtd restart)
#=====#


#=====#
#create custom manifest
